defaults:
  - _self_
  - train: default

project_name: "AI-Real-Image-Classification"
experiment_name: "resnet"
seed : 42

data:
  root_dir: "data" # change later once we uploaded the data
  num_classes: 1
  img_size: 224
  train_split: 0.7
  val_split: 0.2
