name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Extract Metadata for Trainer
        id: meta-trainer
        uses: docker/metadata-action@v5
        with:
          images: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/images/trainer
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha

      - name: Build and Push Trainer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/trainer.dockerfile
          push: true
          tags: ${{ steps.meta-trainer.outputs.tags }}
          labels: ${{ steps.meta-trainer.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Metadata for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/images/api
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/api.dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
